version: "3"
services:
  springpart:
    build: .
    ports:
      - '8077:8077'
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    networks:
      - backend
      - frontend
    depends_on: 
      - db
    restart: on-failure
  db:
    image: mysql:8.0.17
    volumes:
    - ./src/main/resources/libraryData/initial:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=library
    networks:
      - backend
  angularpart:
    build: ./librarymanagement-angular-master@9742209ec6a
    ports:
    - '4200:80'
    networks:
      - frontend
networks:
  frontend:
  backend:




